fail_fast: true
repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        language: system
        files: "^(?:rhombusaitestapp|tests)/"
        exclude: "migrations"
        types: [python]
        entry: poetry
        args: ["run", "ruff", "check"]

      - id: pylint
        name: pylint
        language: system
        files: "^(?:rhombusaitestapp|tests)/"
        exclude: "migrations"
        types: [python]
        entry: env PYTHONPATH=./rhombusaitestapp:$PYTHONPATH poetry
        args:
          [
            "run",
            "pylint",
            "-sn",
            "--django-settings-module=rhombusaitestapp.settings",
          ]
