# Generated by Django 5.1.2 on 2024-11-02 11:47

from django.db import migrations, models

import inference.constants


class Migration(migrations.Migration):

    dependencies = [
        ("inference", "0002_datafile_datatype_remove_employee_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datafile",
            name="processing_status",
            field=models.CharField(choices=inference.constants.ProcessingStatus.choices, default=inference.constants.ProcessingStatus["IDLE"], max_length=20),
        ),
    ]
